config/routes.rb
Rails.application.routes.draw do
  get "useful/index"
  root "home#index"

  get "notification_settings/show"
  get "notification_settings/update"
  get "notifications/index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  # デモモード
  devise_scope :user do
    post "demo_login", to: "users/sessions#demo", as: :demo_login
  end

  get "main", to: "main#index"

  # ペアID登録ページ(新規登録後専用)
  get "onboarding/pair", to: "onboarding#pair", as: :onboarding_pair
  post "onboarding/pair", to: "onboarding#create_pair"
  get "onboarding/skip", to: "onboarding#skip", as: :onboarding_skip


  resources :users, only: [ :show, :edit, :update ] do
    post :regenerate_code, on: :member
  end

  resource :user, only: [ :destroy ]

  resources :pairs, only: [ :new, :create, :destroy ]
  resources :posts, only: [ :new, :create, :show, :edit, :update, :destroy ]
  resources :post_memos, only: [ :create, :update ]

  resources :notifications, only: [ :index ] do
    member do
      patch :mark_as_read  # ← memberブロック内に定義
    end
    collection do
      patch :mark_all_as_read
    end
  end

  resource :notification_settings, only: [ :show, :update ]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  resources :anniversaries, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]

  resource :board, only: [ :show, :update ]

  # お役立ちページの分岐
  get "useful", to: "useful#index", as: :useful

  # 今日できる簡単なこと
  get "daily_tasks", to: "daily_tasks#index"

  # ルールブック
  resources :rule_items, only: [ :index, :new, :create, :edit, :update, :destroy ]

  # 静的ページ
  get "about",   to: "pages#about"
  get "contact", to: "pages#contact"
  get "terms",   to: "pages#terms"
  get "privacy", to: "pages#privacy"

  # 投稿プリセット
  resources :presets, only: [ :index, :new, :create, :edit, :update, :destroy ]

  # アーカイブ
  resources :posts, only: [ :show, :edit, :update, :destroy ] do
    member do
      patch :toggle_archive
    end
  end

  get "main/archive", to: "main#archive", as: :archive_posts

  resources :push_subscriptions, only: [:create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to main_path if user_signed_in?
  end
end

app/views/home/index.html.erb
<div class="min-h-screen bg-light-cream py-16 px-6">

  <!-- ヒーロー -->
  <div class="max-w-3xl mx-auto text-center mb-10">
    <p class="text-center text-sm text-accent-orange underline decoration-dotted decoration-2 underline-offset-4 mb-4">
      小さな気づきを貯めて、そっと背中を押す
    </p>
    <h1 class="text-5xl font-fui text-forest-green mb-10">ふたりの察し手帳</h1>
    <div class="flex justify-center gap-4">
      <%= link_to "ログイン", new_user_session_path, class: "btn btn-secondary" %>
    </div>
  </div>

  <!-- Howto -->
  <section class="py-20 mb-10">
  <div class="text-center mb-16">
    <h2 class="text-3xl font-semibold text-forest-green">
      How to
    </h2>
  </div>

    <div class="max-w-4xl mx-auto px-4 space-y-20">

      <!-- item -->
      <div class="flex flex-col-reverse md:flex-row items-center gap-10">
        <!-- イラスト  -->
        <div class="w-full md:w-1/2 h-48 bg-white/60 rounded-xl z-10">
        <%= image_tag "1170.png", alt: "説明文", class: "w-64" %>
        </div>

        <!-- text -->
        <div class="w-full md:w-1/2 relative">
          <div class="absolute -top-10 -left-10">
            <!-- big circle -->
            <span class="absolute -top-3 -left-3 w-24 h-24 rounded-full bg-accent-orange/20 z-0"></span>
            <!-- number -->
            <span class="relative block w-24 h-24 flex items-center justify-center
                        text-accent-orange font-semibold text-4xl">
              1
            </span>
          </div>

          <h4 class="font-semibold text-2xl mb-3 mt-6">普段言えないことをメモ</h4>
          <p class="text-sm text-gray-600 leading-relaxed">
            「前髪を切った」「お風呂掃除した」など、<br>
            相手に気づいてほしいことを気軽にさっと残します。
          </p>
        </div>
      </div>


      <!-- item -->
      <div class="flex flex-col-reverse md:flex-row-reverse items-center gap-10">
        <!-- イラスト  -->
        <div class="w-full md:w-1/2 h-48 bg-white/60 rounded-xl z-10">
        <%= image_tag "1561.png", alt: "説明文", class: "w-64" %>
        </div>

        <!-- text -->
        <div class="w-full md:w-1/2 relative">
          <div class="absolute -top-10 -left-10">
            <!-- big circle -->
            <span class="absolute -top-3 -left-3 w-24 h-24 rounded-full bg-accent-orange/20 z-0"></span>
            <!-- number -->
            <span class="relative block w-24 h-24 flex items-center justify-center
                        text-accent-orange font-semibold text-4xl">
              2
            </span>
          </div>

          <h4 class="font-semibold text-2xl mb-3 mt-6">すぐに表示されない “ぼかし通知”</h4>
          <p class="text-sm text-gray-600 leading-relaxed">
            投稿しても内容はすぐに公開されません。<br>
            まずはヒントだけが表示され、<br>
            相手は「何だろう？」と自然に考え始めます。
          </p>
        </div>
      </div>


      <!-- item -->
      <div class="flex flex-col-reverse md:flex-row items-center gap-10">
        <!-- イラスト  -->
        <div class="w-full md:w-1/2 h-48 bg-white/60 rounded-xl z-10">
        <%= image_tag "622.png", alt: "説明文", class: "w-64" %>
        </div>

        <!-- text -->
        <div class="w-full md:w-1/2 relative">
          <div class="absolute -top-10 -left-10">
            <!-- big circle -->
            <span class="absolute -top-3 -left-3 w-24 h-24 rounded-full bg-accent-orange/20 z-0"></span>
            <!-- number -->
            <span class="relative block w-24 h-24 flex items-center justify-center
                        text-accent-orange font-semibold text-4xl">
              3
            </span>
          </div>

          <h4 class="font-semibold text-2xl mb-3 mt-6">答え合わせが、やさしい気づきに</h4>
          <p class="text-sm text-gray-600 leading-relaxed">
            決められた時間になるとメモの内容が表示されます。<br>
          「あ、これのことだったんだ」<br>
          そんな小さな発見が生まれます。
          </p>
        </div>
      </div>


      <!-- item -->
      <div class="flex flex-col-reverse md:flex-row-reverse items-center gap-10">
        <!-- イラスト  -->
        <div class="w-full md:w-1/2 h-48 bg-white/60 rounded-xl z-10">
        <%= image_tag "734.png", alt: "説明文", class: "w-64" %>
        </div>

        <!-- text -->
        <div class="w-full md:w-1/2 relative">
          <div class="absolute -top-10 -left-10">
            <!-- big circle -->
            <span class="absolute -top-3 -left-3 w-24 h-24 rounded-full bg-accent-orange/20 z-0"></span>
            <!-- number -->
            <span class="relative block w-24 h-24 flex items-center justify-center
                        text-accent-orange font-semibold text-4xl">
              4
            </span>
          </div>

          <h4 class="font-semibold text-2xl mb-3 mt-6 ">リアルなコミュニケーションを育てる</h4>
          <p class="text-sm text-gray-600 leading-relaxed">
            察してほしい、でも押しつけたくない。<br>
            その間にある、ちょうどいい距離感。<br>
            自然にお互いを理解するきっかけをつくります。
          </p>
        </div>
      </div>


    </div>
  </section>



  <section class="py-20 mb-10">
    <div class="text-center mb-16">
      <h2 class="text-3xl font-semibold text-forest-green">
        このアプリでできること
      </h2>
    </div>

    <!-- 特徴カード -->
    <div class="max-w-5xl mx-auto grid gap-12 md:grid-cols-2">

      <!-- カード1 -->
      <div class="card-notebook bg-white flex flex-col items-start gap-3 p-10">
        <div class="flex items-center gap-2">
          <span class="text-2xl">✏️</span>
          <h2 class="text-2xl font-semibold text-forest-green">
          言葉にしなくても気持ちが伝わる</h2>
        </div>
        <p class="text-forest-green">
          面と向かって言うほどではないこと、
          言うと気を遣わせてしまいそうなことなど
          相手を思いやる気持ちを
          安心して置いておける場所です。
        </p>
      </div>

      <!-- カード2 -->
      <div class="card-notebook bg-white flex flex-col items-start gap-3 p-10">
        <div class="flex items-center gap-2">
          <span class="text-2xl">🧠</span>
          <h2 class="text-2xl font-semibold text-forest-green">
          「察してほしい」を負担にしない</h2>
        </div>
        <p class="text-forest-green">このアプリはあえてすぐ通知をしません。
          ヒントだけを届けることで、相手が自分の意思で気づく余白を残します。</p>
      </div>

      <!-- カード3 -->
      <div class="card-notebook bg-white flex flex-col items-start gap-3 p-10">
        <div class="flex items-center gap-2">
          <span class="text-2xl">⏳</span>
          <h2 class="text-2xl font-semibold text-forest-green">
          正解を求めないコミュニケーション</h2>
        </div>
        <p class="text-forest-green"> 察してもらう必要も、察しなければならない義務もありません。
        当たった・外れたではなく、考えた時間そのものを大切にします。</p>
      </div>

      <!-- カード4 -->
      <div class="card-notebook bg-white flex flex-col items-start gap-3 p-10">
        <div class="flex items-center gap-2">
          <span class="text-2xl">💬</span>
          <h2 class="text-2xl font-semibold text-forest-green">小さな気づきが、関係を育てる</h2>
        </div>
        <p class="text-forest-green">アプリの中で完結しない体験。小さな気づきが会話のきっかけになります。
        日常のコミュニケーションを、無理なく、少しずつやわらかくします。</p>
      </div>

    </div>
  </section>

  
  <div class="flex flex-col items-center gap-2">
    <p>早速はじめてみましょう！</p>
    <%= link_to "ログイン", new_user_session_path, class: "btn btn-secondary" %>
  </div>

</div>


<footer class="bg-forest-green py-8">
  <div class="max-w-5xl mx-auto px-4 text-center space-y-4">
    <!-- privacy policy -->
    <%= link_to "運営元", about_path, class:"text-wood-light text-sm hover:underline" %>
     / 
    <%= link_to "お問い合わせ", contact_path, class:"text-wood-light text-sm hover:underline" %>
     / 
    <%= link_to "利用規約", terms_path, class:"text-wood-light text-sm hover:underline" %>
     / 
    <%= link_to "プライバシーポリシー", privacy_path, class:"text-wood-light text-sm hover:underline" %>

    <!-- copyright -->
    <p class="text-wood-light text-xs">
      © 2026 ふたりのきっかけ帳
    </p>
  </div>
</footer>